/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SecurityFunctions */

#ifndef _Included_SecurityFunctions
#define _Included_SecurityFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SecurityFunctions
 * Method:    encrypt
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_SecurityFunctions_encrypt
  (JNIEnv *, jclass, jintArray, jintArray);

/*
 * Class:     SecurityFunctions
 * Method:    decrypt
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_SecurityFunctions_decrypt
  (JNIEnv *, jclass, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
